name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: hello
        run: echo "hello  from ${{ github.workflow }} triggered by ${{ github.event_name }}

      - name: compile
        working-directory: ./
        run: mvn compile