name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3


    steps:
      - uses: actions/checkout@v2

      - name: set up jdk 1.8
        uses: actions/setup-java@v1
        whit:
          java-version: 1.8

      - name: Compile with maven
        working-directory: ./
        run: mvn compile

      - name: Tests
        working-directory: ./
        run: mvn test

      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker Image
        run: docker build -t data-service-backend .

      - name: Tags
        run: |
          docker tag data-service-backend ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag data-service-backend ${{ secrets.DOCKER_USER }}/back:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest