name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: build with maven
        working-directory: ./
        run: mvn build

      - name: Tests
        working-directory: ./
        run: mvn test

      - name: package with maven
        working-directory: ./
        run: mvn clean package

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build docker Image
        run: docker build -t data-service-backend .

      - name: Tags
        run: |
          docker tag data-service-backend ${{ secrets.DOCKER_USERNAME }}/back:${{ github.sha }}
          docker tag data-service-backend ${{ secrets.DOCKER_USERNAME }}/back:latest

      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest