name: workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: compile
        working-directory: ./
        run: mvn compile

      - name: tests
        working-directory: ./
        run: mvn test
